services:
  
  db:
    image: postgres
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - raminagrobisVolume:/var/lib/postgresql/data
      
  cache:
       image: redis/redis-stack
       ports:
         - "6379:6379"
         - "8001:8001"
       #environment:
         #- REDIS_ARGS="--requirepass motdepasse"   
   
  monitoring:
        image: louislam/uptime-kuma
        ports:
          - "3001:3001"
        volumes:
          - uptimeKumaRaminagrobis:/app/data
#  back:
#    build: ./Back
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db

volumes:
  raminagrobisVolume:
  uptimeKumaRaminagrobis:
