services:
  
  db:
    image: postgres
    ports:
      - "5442:5432"
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - raminagrobisVolume:/var/lib/postgresql/data

volumes:
  raminagrobisVolume:
